# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [ ]:
np.zeros(10)

3. Create a vector with values ranging from 10 to 49

In [ ]:
x=np.arange(10,50)
x

4. Find the shape of previous array in question 3

In [ ]:
np.shape(x)

5. Print the type of the previous array in question 3

In [ ]:
type(x)

6. Print the numpy version and the configuration


In [ ]:
print(np.__version__)
print(np.show_config())

7. Print the dimension of the array in question 3


In [ ]:
np.ndim(x)

8. Create a boolean array with all the True values

In [ ]:
np.ones(10,dtype=bool)

9. Create a two dimensional array




In [ ]:
x=np.random.randn(2,2)
x

In [ ]:
x.ndim

10. Create a three dimensional array



In [ ]:
x=np.random.randn(3,3,3)
x

In [ ]:
x.ndim

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [ ]:
x=np.array([1,2,3,4,5])
print(x)
x[::-1]


12. Create a null vector of size 10 but the fifth value which is 1 

In [ ]:
x=np.zeros(10)
x[-1]=1
x

13. Create a 3x3 identity matrix

In [ ]:
np.identity(3)

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr.astype(float)

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [ ]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr1*arr2

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [ ]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
new=arr1==arr2
new

17. Extract all odd numbers from arr with values(0-9)

In [ ]:
x=np.arange(0,10)
x=x[x % 2 == 1]
x

18. Replace all odd numbers to -1 from previous array

In [ ]:
x[::]=-1
x

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [ ]:
arr = np.arange(10)
print(arr)
arr[5:9]=12
arr

20. Create a 2d array with 1 on the border and 0 inside

In [ ]:
x=np.ones((4,4))
x[1:-1,1:-1]=0
x

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [ ]:
arr2d = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
arr2d.ndim
arr2d [arr2d >= 5] = 55
arr2d 

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [ ]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0][0:1]=64
arr3d

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [ ]:
x=np.array([0,1,2,3,4,5,6,7,8,9])
x=x.reshape(2,-1)
print(x)
x[0]

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [ ]:
x=np.array([0,1,2,3,4,5,6,7,8,9])
x=x.reshape(2,-1)
print(x)
x[1][1]

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [ ]:
x=np.array([0,1,2,3,4,5,6,7,8,9])
x=x.reshape(2,-1)
print(x)
x[:,3]

26. Create a 10x10 array with random values and find the minimum and maximum values

In [ ]:
randnums= np.random.randint(1,500, size=(10,10))
print(f"min value is {randnums.min()}")
print(f"min value is {randnums.max()}")

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a, b)) 

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)

In [ ]:
print(names)  
print(data)
print(names == 'Will')
data[names == 'Will']

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names != ['Joe','Will']


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [ ]:
arr = np.arange(1,16)
arr.reshape(5,3)

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [ ]:
arr = np.arange(1,17)
x=arr.reshape(2,2,4)
x

33. Swap axes of the array you created in Question 32

In [ ]:
x.ndim

In [ ]:
x.transpose()

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [ ]:
x=np.arange(10)
x=np.sqrt(x)
x[x<.5]=0
x

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [ ]:
a=np.random.rand(12)
b=np.random.rand(12)

In [ ]:
print(a)
print(b)

In [ ]:
x=[]
for i in [a,b]:
    x=i.max()
print(x)

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
x=np.unique(names)
x=np.sort(x)
x

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [52]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])

In [59]:
x=np.intersect1d(a,b)
a = delete(a, x)
a

NameError: name 'delete' is not defined

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [28]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 


sampleArray=np.delete(sampleArray, 1)
sampleArray

array([34, 73, 82, 22, 12, 53, 94, 66])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [18]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [14]:
x=np.random.randn(20)
x

array([-0.16563906,  0.03309111,  1.23989453, -0.3534593 , -1.7313103 ,
       -0.23235967, -0.37114639, -0.30902841, -0.79889038, -0.95081983,
       -0.42804239,  1.4973154 ,  0.87092556,  0.22823972,  0.19151439,
       -2.85928853, -1.37559757, -1.07541805,  0.09913206,  0.52574812])

In [15]:
np.cumsum(x)

array([-0.16563906, -0.13254795,  1.10734658,  0.75388728, -0.97742302,
       -1.20978269, -1.58092908, -1.8899575 , -2.68884788, -3.6396677 ,
       -4.06771009, -2.57039469, -1.69946913, -1.47122941, -1.27971502,
       -4.13900356, -5.51460112, -6.59001917, -6.49088711, -5.965139  ])