# Numpy_Assignment_2::

In [4]:
import numpy as np

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [9]:
x=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
x.ndim

1

In [25]:
x=np.reshape(x,(2,5))
print(x)
print(x.ndim)

[[0 1 2 3 4]
 [5 6 7 8 9]]
2


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [34]:
x1=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]).reshape(2,5)
x2=np.array([10,11, 12, 13, 14, 15, 16, 17, 18, 19]).reshape(2,5)


In [35]:
np.vstack((x1,x2))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [36]:
x1=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x2=np.array([10,11, 12, 13, 14, 15, 16, 17, 18, 19])
np.vstack((x1,x2))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [40]:
f=np.vstack((x1,x2))
np.ravel(f)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [43]:
np.array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]]).ravel()

array([0, 1, 2, 3, 4, 1, 1, 1, 1, 1, 5, 6, 7, 8, 9, 1, 1, 1, 1, 1])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [44]:
np.array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]).reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [98]:
x=np.random.randn(25).reshape(5,5)*5
np.array(x)
x=np.square(x)
x

array([[1.41590191e+01, 4.05652571e-01, 1.08521973e+02, 3.61591293e+01,
        1.36890040e+01],
       [1.35903456e-01, 4.55884108e+00, 3.94359213e+01, 7.66225775e+00,
        3.18580124e+01],
       [1.66839823e+02, 3.23551339e+01, 4.32595013e+01, 4.18131840e+01,
        3.27107296e+00],
       [1.99319133e-01, 6.60408686e+00, 7.74296861e+01, 3.26973313e+01,
        7.39703025e+00],
       [8.33214125e+00, 8.96719894e-01, 6.36639358e-01, 1.16234659e+01,
        1.53305477e+01]])

## Question:8

### Create 5x6 an array and find the mean?

In [101]:
x=np.random.randn(25).reshape(5,5)*5
x=np.array(x)
m=np.mean(x)
m

0.5128167898312582

In [103]:
x

array([[-4.70902266e+00, -1.00485901e+01,  9.08961985e+00,
         5.04604352e-03, -3.16023843e+00],
       [-7.91219548e+00,  1.07852209e+01,  4.49357604e+00,
        -8.70056124e+00,  5.61832404e+00],
       [ 3.17865196e+00,  3.78184465e+00,  8.46909432e-02,
         7.15365447e+00, -1.16784395e+00],
       [ 6.60916711e+00,  1.34262736e+00, -4.29475979e+00,
        -2.52884048e+00, -1.29016888e-01],
       [ 6.81380098e+00,  6.35922148e+00, -8.86218905e+00,
        -2.27260832e+00,  1.29084030e+00]])

## Question:9

### Find the standard deviation of the previous array in Q8?

In [105]:
np.std(x)

5.779597186691459

## Question:10

### Find the median of the previous array in Q8?

In [107]:
np.median(x)

0.08469094323944751

## Question:11

### Find the transpose of the previous array in Q8?

In [109]:
x

array([[-4.70902266e+00, -1.00485901e+01,  9.08961985e+00,
         5.04604352e-03, -3.16023843e+00],
       [-7.91219548e+00,  1.07852209e+01,  4.49357604e+00,
        -8.70056124e+00,  5.61832404e+00],
       [ 3.17865196e+00,  3.78184465e+00,  8.46909432e-02,
         7.15365447e+00, -1.16784395e+00],
       [ 6.60916711e+00,  1.34262736e+00, -4.29475979e+00,
        -2.52884048e+00, -1.29016888e-01],
       [ 6.81380098e+00,  6.35922148e+00, -8.86218905e+00,
        -2.27260832e+00,  1.29084030e+00]])

In [110]:
x.T

array([[-4.70902266e+00, -7.91219548e+00,  3.17865196e+00,
         6.60916711e+00,  6.81380098e+00],
       [-1.00485901e+01,  1.07852209e+01,  3.78184465e+00,
         1.34262736e+00,  6.35922148e+00],
       [ 9.08961985e+00,  4.49357604e+00,  8.46909432e-02,
        -4.29475979e+00, -8.86218905e+00],
       [ 5.04604352e-03, -8.70056124e+00,  7.15365447e+00,
        -2.52884048e+00, -2.27260832e+00],
       [-3.16023843e+00,  5.61832404e+00, -1.16784395e+00,
        -1.29016888e-01,  1.29084030e+00]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [156]:
x=np.random.randn(16).reshape(4,4)*5
x=np.array(x)
x

array([[ 2.41815717,  4.32668378, -4.34213876,  3.71481241],
       [ 4.89111769,  5.71005235, -2.70824675,  3.38935847],
       [ 5.97046947, -1.10029716, -5.84329069,  0.08353513],
       [-2.51744933, -1.66524337,  0.99208261, -2.84982283]])

In [157]:
np.diagonal(x)

array([ 2.41815717,  5.71005235, -5.84329069, -2.84982283])

In [158]:
np.diagonal(x).sum()

-0.5649039961700693

## Question:13

### Find the determinant of the previous array in Q12?

In [159]:
x

array([[ 2.41815717,  4.32668378, -4.34213876,  3.71481241],
       [ 4.89111769,  5.71005235, -2.70824675,  3.38935847],
       [ 5.97046947, -1.10029716, -5.84329069,  0.08353513],
       [-2.51744933, -1.66524337,  0.99208261, -2.84982283]])

In [160]:
x.shape


(4, 4)

In [162]:
np.linalg.det(x)

-280.1010600990066

## Question:14

### Find the 5th and 95th percentile of an array?

In [163]:
x

array([[ 2.41815717,  4.32668378, -4.34213876,  3.71481241],
       [ 4.89111769,  5.71005235, -2.70824675,  3.38935847],
       [ 5.97046947, -1.10029716, -5.84329069,  0.08353513],
       [-2.51744933, -1.66524337,  0.99208261, -2.84982283]])

In [168]:
print("5th percentile",np.percentile(x, 5))
print("95th percentile",np.percentile(x, 95))

5th percentile -4.717426742878567
95th percentile 5.775156633655551


## Question:15

### How to find if a given array has any null values?